# Generated by Django 5.2.1 on 2025-05-17 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0002_alter_roomimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occupieddate',
            options={'verbose_name': 'Occupied Date', 'verbose_name_plural': 'Occupied Dates'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomimage',
            options={'verbose_name': 'Room Image', 'verbose_name_plural': 'Room Images'},
        ),
        migrations.AlterField(
            model_name='occupieddate',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='occupieddate',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupiedDates', to='room_booking.room', verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='occupieddate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_dates', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='room',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], default='USD', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='maxOccupancy',
            field=models.IntegerField(default=1, verbose_name='Maximum Occupancy'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='pricePerNight',
            field=models.IntegerField(default=150, verbose_name='Price per Night'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('suite', 'Suite'), ('standard', 'Standard Room'), ('deluxe', 'Deluxe Room')], max_length=100, verbose_name='Room Type'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(upload_to='room_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='room_booking.room', verbose_name='Room'),
        ),
    ]
